<a href="https://colab.research.google.com/github/akashvalmikinayak/AIML/blob/main/AIML_LAB_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
type(A3)

numpy.ndarray

In [ ]:
z1=np.zeros(3,dtype=int)
z1


array([0, 0, 0])

In [ ]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
import numpy as np
al=np.ones(3)
al

array([1., 1., 1.])

In [ ]:
np.array([1.,1.,1.])

array([1., 1., 1.])

In [ ]:
a2=np.ones([1,2,3])
a2

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a2.shape

(1, 2, 3)

In [ ]:
a2.size

6

In [ ]:
import numpy as np


A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
a3=np.ones([4,5,7])
a3

array([[[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]])

In [ ]:
a3.shape

(4, 5, 7)

In [ ]:
a3.size

140